name: Public_Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install Pulp
      run: |
        python -m pip install --upgrade pip
        pip install pulp

    - name: Install GLPK
      run: |
        sudo apt-get update
        sudo apt-get install -y glpk-utils

    - name: Run tests
      run: |
        python -m pytest -v --tb=short ./src/tests/test_public.py